import type { ControlRow } from '@/widgets/WorkpaperGrid/types';

const AUDITORS = [
  { id: 'a1', name: 'Ahmet Yılmaz', initials: 'AY', color: 'bg-blue-600' },
  { id: 'a2', name: 'Ayşe Demir',   initials: 'AD', color: 'bg-emerald-600' },
  { id: 'a3', name: 'Burak Şahin',  initials: 'BŞ', color: 'bg-amber-600' },
  { id: 'a4', name: 'Selin Arslan', initials: 'SA', color: 'bg-rose-600' },
];

export const IT_CONTROLS: ControlRow[] = [
  {
    id: 'it-001', control_id: 'IT-001',
    title: 'Şifre Karmaşıklık Politikası',
    description: 'Minimum uzunluk, karmaşıklık gereksinimleri ve son kullanma tarihlerini kapsayan şifre politikalarının sistem genelinde etkin biçimde uygulandığını doğrular.',
    category: 'Access Control', risk_level: 'HIGH',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 25,
    auditor: AUDITORS[0],
  },
  {
    id: 'it-002', control_id: 'IT-002',
    title: 'Çok Faktörlü Kimlik Doğrulama',
    description: 'MFA\'nın kritik sistemlerde uygulandığını, muafiyet listesinin kontrol altında olduğunu ve bypass mekanizmalarının bulunmadığını doğrular.',
    category: 'Access Control', risk_level: 'HIGH',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 30,
    auditor: AUDITORS[1],
  },
  {
    id: 'it-003', control_id: 'IT-003',
    title: 'Kullanıcı Erişim Gözden Geçirmesi',
    description: 'Periyodik kullanıcı erişim incelemelerinin zamanında gerçekleştirildiğini ve sonuçların uygulandığını doğrular.',
    category: 'Access Control', risk_level: 'HIGH',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 20,
    auditor: AUDITORS[0],
  },
  {
    id: 'it-004', control_id: 'IT-004',
    title: 'Ayrıcalıklı Hesap Yönetimi',
    description: 'Süper kullanıcı ve yönetici hesaplarının gerekçelendirildiğini, izlendiğini ve güvenli şekilde yönetildiğini doğrular.',
    category: 'Access Control', risk_level: 'HIGH',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 15,
    auditor: AUDITORS[2],
  },
  {
    id: 'it-005', control_id: 'IT-005',
    title: 'Güvenlik Duvarı Kural Gözden Geçirmesi',
    description: 'Güvenlik duvarı kural setinin belgelendiğini, gözden geçirildiğini ve gereksiz açık portların kapatıldığını doğrular.',
    category: 'Network Security', risk_level: 'HIGH',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 10,
    auditor: AUDITORS[1],
  },
  {
    id: 'it-006', control_id: 'IT-006',
    title: 'Yama Yönetimi',
    description: 'Kritik güvenlik yamalarının politika belirtilen süre içinde uygulandığını ve yama uyum oranının kabul edilebilir düzeyde olduğunu doğrular.',
    category: 'Endpoint Security', risk_level: 'HIGH',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 20,
    auditor: AUDITORS[3],
  },
  {
    id: 'it-007', control_id: 'IT-007',
    title: 'Değişiklik Yönetimi Süreci',
    description: 'Tüm değişikliklerin onaylandığını, test edildiğini ve değişiklik panosu kararlarının mevcut olduğunu doğrular.',
    category: 'Change Management', risk_level: 'MEDIUM',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 25,
    auditor: AUDITORS[2],
  },
  {
    id: 'it-008', control_id: 'IT-008',
    title: 'Yedekleme ve Kurtarma',
    description: 'Kritik sistemlerin düzenli olarak yedeklendiğini ve kurtarma prosedürlerinin periyodik olarak test edildiğini doğrular.',
    category: 'Business Continuity', risk_level: 'HIGH',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 5,
    auditor: AUDITORS[0],
  },
  {
    id: 'it-009', control_id: 'IT-009',
    title: 'Olay Yanıt Prosedürleri',
    description: 'Güvenlik olaylarının tanımlandığını, raporlandığını ve olay yanıt planına göre yönetildiğini doğrular.',
    category: 'Governance', risk_level: 'MEDIUM',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 10,
    auditor: AUDITORS[3],
  },
  {
    id: 'it-010', control_id: 'IT-010',
    title: 'Fiziksel Güvenlik Kontrolleri',
    description: 'Veri merkezine yetkisiz erişimin engellendiğini, giriş kayıtlarının tutulduğunu ve fiziksel kontrollerin çalışır durumda olduğunu doğrular.',
    category: 'Physical Security', risk_level: 'MEDIUM',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 8,
    auditor: AUDITORS[1],
  },
  {
    id: 'it-011', control_id: 'IT-011',
    title: 'Veri Şifreleme Standartları',
    description: 'Hassas verilerin hem bekleme (at-rest) hem de iletim (in-transit) sırasında onaylı şifreleme algoritmaları ile korunduğunu doğrular.',
    category: 'Data Protection', risk_level: 'HIGH',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 20,
    auditor: AUDITORS[2],
  },
  {
    id: 'it-012', control_id: 'IT-012',
    title: 'Ağ Segmentasyonu',
    description: 'VLAN\'ların ve ağ bölümleme kontrollerinin kritik sistemleri izole ettiğini ve yanal hareket saldırılarına karşı koruma sağladığını doğrular.',
    category: 'Network Security', risk_level: 'MEDIUM',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 15,
    auditor: AUDITORS[0],
  },
  {
    id: 'it-013', control_id: 'IT-013',
    title: 'Güvenlik Açığı Yönetimi',
    description: 'Güvenlik açığı taramalarının düzenli yapıldığını ve tespit edilen kritik açıkların SLA süresi içinde giderildiğini doğrular.',
    category: 'Monitoring', risk_level: 'HIGH',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 30,
    auditor: AUDITORS[3],
  },
  {
    id: 'it-014', control_id: 'IT-014',
    title: 'Üçüncü Taraf Erişim Denetimi',
    description: 'Satıcı ve üçüncü taraf erişiminin gerektiğinde verildiğini, izlendiğini ve iş ilişkisi sona erdiğinde iptal edildiğini doğrular.',
    category: 'Access Control', risk_level: 'MEDIUM',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 12,
    auditor: AUDITORS[1],
  },
  {
    id: 'it-015', control_id: 'IT-015',
    title: 'Log Yönetimi ve İzleme',
    description: 'Güvenlik loglarının merkezi olarak toplandığını, korunduğunu ve güvenlik olayları için zamanında uyarıların oluşturulduğunu doğrular.',
    category: 'Monitoring', risk_level: 'HIGH',
    tod: 'NOT_STARTED', toe: 'NOT_STARTED', sample_size: 25,
    auditor: AUDITORS[2],
  },
];
