import type { AuditEntity } from '../model/types';

const MOCK_TENANT_ID = '11111111-1111-1111-1111-111111111111';
const MOCK_USER_ID = '00000000-0000-0000-0000-000000000002';

export const mockUniverseData: AuditEntity[] = [
  {
    id: '1',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding',
    name: 'Global Financial Holding',
    type: 'HOLDING',
    risk_score: 65.4,
    velocity_multiplier: 1.15,
    owner_id: MOCK_USER_ID,
    metadata: { country: 'TR', employees: 45000 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '2',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank',
    name: 'Commercial Banking Corp',
    type: 'BANK',
    risk_score: 72.3,
    velocity_multiplier: 1.25,
    owner_id: MOCK_USER_ID,
    metadata: { license: 'CB-2024', total_assets: '450B' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '3',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.retail',
    name: 'Retail Banking Division',
    type: 'GROUP',
    risk_score: 68.7,
    velocity_multiplier: 1.20,
    owner_id: MOCK_USER_ID,
    metadata: { branches: 850, customers: '12M' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '4',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.retail.consumer_lending',
    name: 'Consumer Lending Unit',
    type: 'UNIT',
    risk_score: 75.2,
    velocity_multiplier: 1.30,
    owner_id: MOCK_USER_ID,
    metadata: { portfolio_size: '45B', default_rate: '2.3%' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '5',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.retail.consumer_lending.mortgage_origination',
    name: 'Mortgage Origination Process',
    type: 'PROCESS',
    risk_score: 82.5,
    velocity_multiplier: 1.40,
    owner_id: MOCK_USER_ID,
    metadata: { volume_monthly: '1200', avg_amount: '250K' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '6',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.retail.consumer_lending.auto_loans',
    name: 'Auto Loan Processing',
    type: 'PROCESS',
    risk_score: 71.8,
    velocity_multiplier: 1.25,
    owner_id: MOCK_USER_ID,
    metadata: { volume_monthly: '3500', avg_amount: '35K' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '7',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.retail.consumer_lending.personal_loans',
    name: 'Personal Loan Underwriting',
    type: 'PROCESS',
    risk_score: 78.3,
    velocity_multiplier: 1.35,
    owner_id: MOCK_USER_ID,
    metadata: { volume_monthly: '5200', avg_amount: '15K' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '8',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.retail.deposit_services',
    name: 'Deposit Services Unit',
    type: 'UNIT',
    risk_score: 58.4,
    velocity_multiplier: 1.10,
    owner_id: MOCK_USER_ID,
    metadata: { total_deposits: '120B', accounts: '8M' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '9',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.retail.deposit_services.account_opening',
    name: 'Account Opening & KYC',
    type: 'PROCESS',
    risk_score: 65.2,
    velocity_multiplier: 1.15,
    owner_id: MOCK_USER_ID,
    metadata: { daily_openings: '450', digital_ratio: '85%' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '10',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.retail.deposit_services.transaction_processing',
    name: 'Transaction Processing',
    type: 'PROCESS',
    risk_score: 54.7,
    velocity_multiplier: 1.08,
    owner_id: MOCK_USER_ID,
    metadata: { daily_volume: '2.5M', avg_processing_time: '0.3s' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '11',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.corporate',
    name: 'Corporate Banking Division',
    type: 'GROUP',
    risk_score: 79.5,
    velocity_multiplier: 1.35,
    owner_id: MOCK_USER_ID,
    metadata: { clients: '1200', portfolio_size: '180B' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '12',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.corporate.large_corporate',
    name: 'Large Corporate Unit',
    type: 'UNIT',
    risk_score: 84.2,
    velocity_multiplier: 1.45,
    owner_id: MOCK_USER_ID,
    metadata: { clients: '150', avg_exposure: '500M' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '13',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.corporate.large_corporate.credit_approval',
    name: 'Corporate Credit Approval',
    type: 'PROCESS',
    risk_score: 88.6,
    velocity_multiplier: 1.50,
    owner_id: MOCK_USER_ID,
    metadata: { avg_decision_time: '7days', approval_rate: '62%' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '14',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.corporate.large_corporate.syndication',
    name: 'Loan Syndication',
    type: 'PROCESS',
    risk_score: 82.1,
    velocity_multiplier: 1.38,
    owner_id: MOCK_USER_ID,
    metadata: { avg_deal_size: '350M', partners: 45 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '15',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.corporate.sme',
    name: 'SME Banking Unit',
    type: 'UNIT',
    risk_score: 76.8,
    velocity_multiplier: 1.28,
    owner_id: MOCK_USER_ID,
    metadata: { clients: '8500', portfolio_size: '28B' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '16',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.corporate.sme.working_capital',
    name: 'Working Capital Loans',
    type: 'PROCESS',
    risk_score: 79.4,
    velocity_multiplier: 1.32,
    owner_id: MOCK_USER_ID,
    metadata: { monthly_volume: '850', avg_amount: '2.5M' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '17',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.commercial_bank.corporate.sme.trade_finance',
    name: 'Trade Finance Operations',
    type: 'PROCESS',
    risk_score: 74.9,
    velocity_multiplier: 1.25,
    owner_id: MOCK_USER_ID,
    metadata: { lc_volume: '1200/month', countries: 85 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '18',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.investment_bank',
    name: 'Investment Banking Corp',
    type: 'BANK',
    risk_score: 85.7,
    velocity_multiplier: 1.55,
    owner_id: MOCK_USER_ID,
    metadata: { license: 'IB-2024', aum: '85B' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '19',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.investment_bank.trading',
    name: 'Trading Division',
    type: 'GROUP',
    risk_score: 91.2,
    velocity_multiplier: 1.70,
    owner_id: MOCK_USER_ID,
    metadata: { daily_volume: '15B', markets: ['FX', 'Equity', 'Fixed Income'] },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '20',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.investment_bank.trading.equity_trading',
    name: 'Equity Trading Unit',
    type: 'UNIT',
    risk_score: 89.5,
    velocity_multiplier: 1.65,
    owner_id: MOCK_USER_ID,
    metadata: { var_limit: '50M', utilization: '78%' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '21',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.investment_bank.trading.equity_trading.execution',
    name: 'Order Execution',
    type: 'PROCESS',
    risk_score: 87.3,
    velocity_multiplier: 1.60,
    owner_id: MOCK_USER_ID,
    metadata: { avg_latency: '12ms', success_rate: '99.97%' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '22',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.investment_bank.trading.equity_trading.risk_monitoring',
    name: 'Real-time Risk Monitoring',
    type: 'PROCESS',
    risk_score: 92.1,
    velocity_multiplier: 1.75,
    owner_id: MOCK_USER_ID,
    metadata: { alerts_daily: '350', false_positive_rate: '15%' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '23',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.investment_bank.trading.derivatives',
    name: 'Derivatives Trading Unit',
    type: 'UNIT',
    risk_score: 94.8,
    velocity_multiplier: 1.80,
    owner_id: MOCK_USER_ID,
    metadata: { notional_value: '250B', counterparties: 120 },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '24',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.investment_bank.trading.derivatives.pricing_valuation',
    name: 'Pricing & Valuation',
    type: 'PROCESS',
    risk_score: 96.2,
    velocity_multiplier: 1.85,
    owner_id: MOCK_USER_ID,
    metadata: { models: 45, validation_frequency: 'daily' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  {
    id: '25',
    tenant_id: MOCK_TENANT_ID,
    path: 'holding.investment_bank.trading.derivatives.collateral_management',
    name: 'Collateral Management',
    type: 'PROCESS',
    risk_score: 93.5,
    velocity_multiplier: 1.75,
    owner_id: MOCK_USER_ID,
    metadata: { margin_calls_daily: '85', total_collateral: '12B' },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
