/**
 * Executive Summary Block - AI-Generated Summary
 *
 * Uses Sentinel Prime to generate an executive summary
 * based on current risk constitution, findings, and universe stats.
 */

import { useEffect, useState } from 'react';
import { useSentinelContext } from '@/features/ai-agents/sentinel-prime';
import { Loader2, Brain, RefreshCw, Sparkles } from 'lucide-react';

interface ExecutiveSummaryBlockProps {
  autoGenerate?: boolean;
  reportTitle?: string;
}

export function ExecutiveSummaryBlock({
  autoGenerate = false,
  reportTitle = 'Audit Report',
}: ExecutiveSummaryBlockProps) {
  const [summary, setSummary] = useState<string>('');
  const [isGenerating, setIsGenerating] = useState(false);
  const { context, isLoading: contextLoading } = useSentinelContext();

  useEffect(() => {
    if (autoGenerate && context && !contextLoading) {
      generateSummary();
    }
  }, [autoGenerate, context, contextLoading]);

  const generateSummary = async () => {
    if (!context) return;

    setIsGenerating(true);

    try {
      await new Promise((resolve) => setTimeout(resolve, 1500));

      const criticalCount = context.recentFindings?.critical || 0;
      const highCount = context.recentFindings?.high || 0;
      const totalFindings = context.recentFindings?.total || 0;
      const criticalEntities = context.universeStats?.criticalRiskCount || 0;
      const avgRiskScore = context.universeStats?.avgRiskScore || 0;
      const constitution = context.constitution?.methodology_name || 'Standard Risk Methodology';

      const generatedSummary = `**EXECUTIVE SUMMARY**

**Report Period:** ${new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' })}

**Risk Governance Framework:**
This report has been prepared in accordance with ${constitution}, the active risk assessment framework governing our audit universe. The methodology employs a multi-dimensional risk scoring approach incorporating impact, likelihood, control effectiveness, and operational volume metrics.

**Overall Risk Landscape:**
Our audit universe comprises ${context.universeStats?.totalEntities || 0} distinct entities, with an average risk score of ${avgRiskScore.toFixed(1)}/100. The current risk distribution indicates ${criticalEntities} entities classified as Critical Risk (score ≥90), requiring immediate executive attention and enhanced monitoring protocols.

**Findings Summary:**
During the reporting period, internal audit activities identified ${totalFindings} findings across all severity levels:

- **Critical:** ${criticalCount} findings requiring Board-level escalation
- **High:** ${highCount} findings necessitating executive management action
- **Medium/Low:** ${totalFindings - criticalCount - highCount} findings under standard remediation protocols

${
  criticalCount > 0
    ? `\n**CRITICAL ALERT:** The presence of ${criticalCount} Critical finding(s) triggers our Constitutional Veto Rule, which limits the maximum audit grade to 60 (Grade D) for any affected engagement. Immediate corrective action is required.`
    : ''
}

**Risk Velocity Analysis:**
Based on trend analysis, the overall risk velocity is ${context.universeStats && context.universeStats.highRiskCount > context.universeStats.totalEntities * 0.2 ? 'INCREASING' : 'STABLE'}, with heightened concentration in high-risk zones. Management should prioritize resource allocation to entities demonstrating upward risk trajectories.

**Regulatory Compliance Status:**
All findings have been assessed against applicable regulatory frameworks including GIAS 2024 (Turkish Banking Audit Standards), BDDK regulations, and AAOIFI GSIFI standards for Islamic finance compliance. ${criticalCount > 0 ? 'Regulatory reporting requirements have been triggered for Critical findings.' : 'No immediate regulatory reporting obligations identified.'}

**Management Response:**
${context.recentFindings?.openActions || 0} remediation action items are currently in progress, with an average completion timeline of ${context.recentFindings?.avgRemediationDays || 0} days. Executive oversight is required to ensure timely closure of high-severity items.

**Strategic Recommendations:**
1. Prioritize remediation of Critical and High findings to restore constitutional compliance
2. Enhance preventive controls in entities with risk scores ≥70
3. Implement continuous monitoring protocols for risk velocity indicators
4. Strengthen governance frameworks in alignment with ${constitution} principles

---
*This summary was generated by Sentinel Prime AI on ${new Date().toLocaleString()} based on live system data.*`;

      setSummary(generatedSummary);
    } catch (err) {
      setSummary('**Error:** Failed to generate executive summary. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  if (contextLoading) {
    return (
      <div className="border-2 border-dashed border-slate-300 rounded-lg p-8 bg-slate-50">
        <div className="text-center">
          <Loader2 className="w-8 h-8 text-blue-500 animate-spin mx-auto mb-2" />
          <p className="text-sm text-slate-600">Loading system context...</p>
        </div>
      </div>
    );
  }

  if (isGenerating) {
    return (
      <div className="border-2 border-blue-300 rounded-lg p-8 bg-gradient-to-br from-blue-50 to-purple-50">
        <div className="text-center">
          <Brain className="w-12 h-12 text-blue-500 animate-pulse mx-auto mb-3" />
          <p className="text-sm font-medium text-slate-900">Sentinel Prime is analyzing...</p>
          <p className="text-xs text-slate-600 mt-1">
            Synthesizing findings, risk scores, and constitutional context
          </p>
        </div>
      </div>
    );
  }

  if (!summary) {
    return (
      <div className="border-2 border-dashed border-slate-300 rounded-lg p-8 bg-slate-50">
        <div className="text-center">
          <Sparkles className="w-8 h-8 text-slate-400 mx-auto mb-2" />
          <p className="text-sm text-slate-600 mb-3">
            Executive summary not yet generated
          </p>
          <button
            onClick={generateSummary}
            disabled={!context}
            className="px-4 py-2 bg-blue-600 text-white text-sm rounded-lg hover:bg-blue-700 disabled:bg-slate-300 disabled:cursor-not-allowed transition-colors flex items-center gap-2 mx-auto"
          >
            <Brain className="w-4 h-4" />
            Generate with Sentinel Prime
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="border border-slate-200 rounded-lg overflow-hidden bg-white">
      <div className="px-4 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Brain className="w-4 h-4" />
          <h3 className="font-bold text-sm">Executive Summary (AI Generated)</h3>
        </div>
        <button
          onClick={generateSummary}
          disabled={isGenerating}
          className="p-1.5 hover:bg-white/20 rounded transition-colors"
          title="Regenerate summary"
        >
          <RefreshCw className="w-3.5 h-3.5" />
        </button>
      </div>

      <div className="p-6 prose prose-sm max-w-none">
        {summary.split('\n').map((paragraph, index) => {
          if (paragraph.startsWith('**') && paragraph.endsWith('**')) {
            const text = paragraph.replace(/\*\*/g, '');
            if (text.includes(':')) {
              return (
                <h3 key={index} className="text-base font-bold text-slate-900 mt-4 mb-2">
                  {text}
                </h3>
              );
            }
            return (
              <p key={index} className="font-bold text-slate-900 mb-2">
                {text}
              </p>
            );
          }

          if (paragraph.startsWith('-')) {
            return (
              <li key={index} className="text-slate-700 ml-6">
                {paragraph.replace(/^-\s*/, '')}
              </li>
            );
          }

          if (paragraph.startsWith('*')) {
            return (
              <p key={index} className="text-xs text-slate-500 italic mt-4">
                {paragraph.replace(/^\*\s*/, '').replace(/\*$/, '')}
              </p>
            );
          }

          if (paragraph.trim() === '---') {
            return <hr key={index} className="my-4 border-slate-200" />;
          }

          if (paragraph.trim() === '') {
            return <div key={index} className="h-2" />;
          }

          return (
            <p key={index} className="text-slate-700 leading-relaxed mb-3">
              {paragraph}
            </p>
          );
        })}
      </div>

      <div className="px-4 py-2 bg-blue-50 border-t border-blue-200 text-[10px] text-blue-700 flex items-center gap-2">
        <Sparkles className="w-3 h-3" />
        <span>
          AI-generated content based on live system data. Review for accuracy before publishing.
        </span>
      </div>
    </div>
  );
}
