import type { RiskLibraryItem } from './types';

const MOCK_TENANT_ID = '00000000-0000-0000-0000-000000000001';
const MOCK_USER_ID = '00000000-0000-0000-0000-000000000002';

export const mockRiskLibraryData: RiskLibraryItem[] = [
  {
    id: 'risk-001',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'CR-001',
    title: 'Kredi Onay Sürecinde Yetkisiz İşlem Riski',
    description:
      'Kredi onay sürecinde yetkilendirme kontrollerin yetersizliği nedeniyle yetkisiz işlem yapılması riski',
    category: 'CREDIT',
    impact_score: 85,
    likelihood_score: 70,
    inherent_score: 92.3,
    control_effectiveness: 0.75,
    residual_score: 23.1,
    tags: ['credit', 'authorization', 'process'],
    created_at: new Date('2024-01-15').toISOString(),
    updated_at: new Date('2024-01-15').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-002',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'OP-001',
    title: 'Operasyonel Hata - Manuel Veri Girişi',
    description:
      'Manuel veri giriş süreçlerinde insan kaynaklı hata yapılması riski',
    category: 'OPERATIONAL',
    impact_score: 65,
    likelihood_score: 80,
    inherent_score: 78.5,
    control_effectiveness: 0.60,
    residual_score: 31.4,
    tags: ['operational', 'data-entry', 'human-error'],
    created_at: new Date('2024-01-16').toISOString(),
    updated_at: new Date('2024-01-16').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-003',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'TR-001',
    title: 'Siber Güvenlik - Sistem Açıklığı Riski',
    description:
      'Kritik bankaçılık sistemlerinde güvenlik açıklığı bulunması ve istismar edilmesi riski',
    category: 'TECHNOLOGY',
    impact_score: 95,
    likelihood_score: 55,
    inherent_score: 88.2,
    control_effectiveness: 0.85,
    residual_score: 13.2,
    tags: ['cybersecurity', 'technology', 'vulnerability'],
    created_at: new Date('2024-01-17').toISOString(),
    updated_at: new Date('2024-01-17').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-004',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'CO-001',
    title: 'Mevzuata Uyumsuzluk - KYC Eksikliği',
    description:
      'Müşteri tanıma (KYC) süreçlerinin mevzuata uygun şekilde yürütülememesi riski',
    category: 'COMPLIANCE',
    impact_score: 90,
    likelihood_score: 45,
    inherent_score: 81.7,
    control_effectiveness: 0.70,
    residual_score: 24.5,
    tags: ['compliance', 'kyc', 'aml'],
    created_at: new Date('2024-01-18').toISOString(),
    updated_at: new Date('2024-01-18').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-005',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'MR-001',
    title: 'Piyasa Riski - Faiz Oranı Değişimi',
    description: 'Faiz oranlarındaki ani değişimler nedeniyle portföy değer kaybı riski',
    category: 'MARKET',
    impact_score: 80,
    likelihood_score: 60,
    inherent_score: 76.8,
    control_effectiveness: 0.65,
    residual_score: 26.9,
    tags: ['market', 'interest-rate', 'portfolio'],
    created_at: new Date('2024-01-19').toISOString(),
    updated_at: new Date('2024-01-19').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-006',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'LR-001',
    title: 'Likidite Riski - Fon Yetersizliği',
    description:
      'Ani nakit çıkışları durumunda yükümlülüklerin karşılanamaması riski',
    category: 'LIQUIDITY',
    impact_score: 85,
    likelihood_score: 40,
    inherent_score: 72.4,
    control_effectiveness: 0.80,
    residual_score: 14.5,
    tags: ['liquidity', 'cash-flow', 'funding'],
    created_at: new Date('2024-01-20').toISOString(),
    updated_at: new Date('2024-01-20').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-007',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'ST-001',
    title: 'Stratejik Risk - Rekabet Kaybı',
    description:
      'Dijital dönüşümde geride kalma nedeniyle pazar payı kaybı riski',
    category: 'STRATEGIC',
    impact_score: 75,
    likelihood_score: 55,
    inherent_score: 69.5,
    control_effectiveness: 0.50,
    residual_score: 34.8,
    tags: ['strategic', 'digital-transformation', 'competition'],
    created_at: new Date('2024-01-21').toISOString(),
    updated_at: new Date('2024-01-21').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-008',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'FR-001',
    title: 'Finansal Raporlama Hatası',
    description: 'Finansal raporlarda yanlış veya eksik bilgi sunulması riski',
    category: 'FINANCIAL',
    impact_score: 88,
    likelihood_score: 35,
    inherent_score: 68.2,
    control_effectiveness: 0.90,
    residual_score: 6.8,
    tags: ['financial', 'reporting', 'accuracy'],
    created_at: new Date('2024-01-22').toISOString(),
    updated_at: new Date('2024-01-22').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-009',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'RR-001',
    title: 'Reputasyon Riski - Sosyal Medya Krizi',
    description:
      'Sosyal medyada olumsuz haberlerin yayılması nedeniyle itibar kaybı riski',
    category: 'REPUTATIONAL',
    impact_score: 70,
    likelihood_score: 50,
    inherent_score: 64.8,
    control_effectiveness: 0.55,
    residual_score: 29.2,
    tags: ['reputation', 'social-media', 'crisis'],
    created_at: new Date('2024-01-23').toISOString(),
    updated_at: new Date('2024-01-23').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-010',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'OP-002',
    title: 'İç Kontrol Zayıflığı - Görevler Ayrılığı',
    description: 'Görevler ayrılığı prensibinin uygulanmaması nedeniyle fraud riski',
    category: 'OPERATIONAL',
    impact_score: 82,
    likelihood_score: 42,
    inherent_score: 71.3,
    control_effectiveness: 0.68,
    residual_score: 22.8,
    tags: ['operational', 'fraud', 'segregation-of-duties'],
    created_at: new Date('2024-01-24').toISOString(),
    updated_at: new Date('2024-01-24').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-011',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'CR-002',
    title: 'Kredi Portföy Yoğunlaşması',
    description:
      'Belirli sektör veya müşterilerde aşırı yoğunlaşma nedeniyle kayıp riski',
    category: 'CREDIT',
    impact_score: 78,
    likelihood_score: 58,
    inherent_score: 73.9,
    control_effectiveness: 0.72,
    residual_score: 20.7,
    tags: ['credit', 'concentration', 'portfolio'],
    created_at: new Date('2024-01-25').toISOString(),
    updated_at: new Date('2024-01-25').toISOString(),
    created_by: MOCK_USER_ID,
  },
  {
    id: 'risk-012',
    tenant_id: MOCK_TENANT_ID,
    risk_code: 'TR-002',
    title: 'BT Altyapı Kesintisi',
    description: 'Kritik BT sistemlerinde kesinti yaşanması riski',
    category: 'TECHNOLOGY',
    impact_score: 92,
    likelihood_score: 38,
    inherent_score: 75.8,
    control_effectiveness: 0.82,
    residual_score: 13.6,
    tags: ['technology', 'infrastructure', 'downtime'],
    created_at: new Date('2024-01-26').toISOString(),
    updated_at: new Date('2024-01-26').toISOString(),
    created_by: MOCK_USER_ID,
  },
];
